const data = {
  path: "V:\\[SORT]\\[PG]\\",
  items: [
    {
      trailer:
        '<a target="_blank" href="http://www.youtube.com/results?search_query=trailer+Batman+%26+Mr.+Freeze%3A+SubZero+1998">trailer</a>',
      year: "1998",
      title: "Batman & Mr. Freeze: SubZero",
      imdb: "http://www.imdb.com/title/tt0143127",
      rating: "PG",
      genre: "Animation",
      actors: "Kevin Conroy, Michael Ansara, Mary Kay Bergman",
      score: "6.9",
      quality: "HD",
      length: "67",
      gigs: "1.08",
      mpaa: "",
      plot: "When Mr. Freeze, desperate to save his dying wife, kidnaps Barbara Gordon (Batgirl) as an involuntary organ donor, Batman and Robin must find her before the operation can begin.",
    },
    {
      trailer:
        '<a target="_blank" href="http://www.youtube.com/results?search_query=trailer+Cats+2019">trailer</a>',
      year: "2019",
      title: "Cats",
      imdb: "http://www.imdb.com/title/tt5697572",
      rating: "PG",
      genre: "Family, Comedy",
      actors: "Francesca Hayward, James Corden, Judi Dench",
      score: "2.7",
      quality: "HD",
      length: "110",
      gigs: "2.12",
      mpaa: "Rated PG for some rude and suggestive humor",
      plot: "A tribe of cats called the Jellicles must decide yearly which one will ascend to the Heaviside Layer and come back to a new Jellicle life.",
    },
    {
      trailer:
        '<a target="_blank" href="http://www.youtube.com/results?search_query=trailer+A+Christmas+Carol+1984">trailer</a>',
      year: "1984",
      title: "Christmas Carol, A",
      imdb: "http://www.imdb.com/title/tt0087056",
      rating: "PG",
      genre: "Family, Fantasy",
      actors: "George C. Scott, Roger Rees, David Warner",
      score: "7.8",
      quality: "HD",
      length: "100",
      gigs: "1.60",
      mpaa: "",
      plot: "An old bitter miser who rationalizes his uncaring nature learns real compassion when three spirits visit him on Christmas Eve.",
    },
    {
      trailer:
        '<a target="_blank" href="http://www.youtube.com/results?search_query=trailer+Dolittle+2020">trailer</a>',
      year: "2020",
      title: "Dolittle",
      imdb: "http://www.imdb.com/title/tt6673612",
      rating: "PG",
      genre: "Family, Comedy",
      actors: "Robert Downey Jr., Antonio Banderas, Michael Sheen",
      score: "5.6",
      quality: "HD",
      length: "101",
      gigs: "1.91",
      mpaa: "Rated PG for some action, rude humor and brief language",
      plot: "A physician who can talk to animals embarks on an adventure to find a legendary island with a young apprentice and a crew of strange pets.",
    },
    {
      trailer:
        '<a target="_blank" href="http://www.youtube.com/results?search_query=trailer+Dragon+Quest%3A+Your+Story+2019">trailer</a>',
      year: "2019",
      title: "Dragon Quest: Your Story",
      imdb: "http://www.imdb.com/title/tt10127562",
      rating: "PG",
      genre: "Family, Animation",
      actors: "Takeru Satoh, Kasumi Arimura, Haru",
      score: "7.0",
      quality: "HD",
      length: "103",
      gigs: "1.84",
      mpaa: "",
      plot: "Based on the fifth Dragon Quest game.",
    },
    {
      trailer:
        '<a target="_blank" href="http://www.youtube.com/results?search_query=trailer+Invasion+Planet+Earth+2019">trailer</a>',
      year: "2019",
      title: "Invasion Planet Earth",
      imdb: "http://www.imdb.com/title/tt3827540",
      rating: "PG",
      genre: "Sci-Fi",
      actors: "Simon Haycock, Lucy Drive, Julie Hoult",
      score: "6.6",
      quality: "HD",
      length: "98",
      gigs: "1.46",
      mpaa: "",
      plot: "After the death of his young daughter, Thomas Dunn is a man who has lost his faith. On the day he finds out his wife is pregnant again, aliens invade the Earth.",
    },
    {
      trailer:
        '<a target="_blank" href="http://www.youtube.com/results?search_query=trailer+Jonathan+2018">trailer</a>',
      year: "2018",
      title: "Jonathan",
      imdb: "http://www.imdb.com/title/tt5639446",
      rating: "PG",
      genre: "Sci-Fi",
      actors: "Ansel Elgort, Suki Waterhouse, Patricia Clarkson",
      score: "6.1",
      quality: "HD",
      length: "95",
      gigs: "1.63",
      mpaa: "",
      plot: "Jonathan leaves the office everyday at noon. When he gets home, he goes to sleep. Every morning he wakes up and there is a breakfast prepared for him along with a video telling him about the second part of his day.",
    },
    {
      trailer:
        '<a target="_blank" href="http://www.youtube.com/results?search_query=trailer+Little+Women+2019">trailer</a>',
      year: "2019",
      title: "Little Women",
      imdb: "http://www.imdb.com/title/tt3281548",
      rating: "PG",
      genre: "Romance",
      actors: "Saoirse Ronan, Florence Pugh, Emma Watson",
      score: "7.9",
      quality: "HD",
      length: "135",
      gigs: "2.40",
      mpaa: "Rated PG for thematic elements and brief smoking.",
      plot: "Jo March reflects back and forth on her life, telling the beloved story of the March sisters - four young women, each determined to live life on her own terms.",
    },
    {
      trailer:
        '<a target="_blank" href="http://www.youtube.com/results?search_query=trailer+Never+Surrender%3A+A+Galaxy+Quest+Documentary+2019">trailer</a>',
      year: "2019",
      title: "Never Surrender: A Galaxy Quest Documentary",
      imdb: "http://www.imdb.com/title/tt11044122",
      rating: "PG",
      genre: "Documentary",
      actors: "Tim Allen, Greg Berlanti, Enrico Colantoni",
      score: "7.1",
      quality: "HD",
      length: "95",
      gigs: "1.41",
      mpaa: "",
      plot: "Filmmakers and stars discuss the filming and social effects of Galaxy Quest, a comedic take-off of Star Trek, with brilliant commentary not only on the Star Trek series but on the real-life actors themselves.",
    },
    {
      trailer:
        '<a target="_blank" href="http://www.youtube.com/results?search_query=trailer+Robot+Carnival+1987">trailer</a>',
      year: "1987",
      title: "Robot Carnival",
      imdb: "http://www.imdb.com/title/tt0093871",
      rating: "PG",
      genre: "Animation",
      actors: "Koji Moritsugu, Keiko Hanagata, Kumiko Takizawa",
      score: "7.0",
      quality: "HD",
      length: "92",
      gigs: "1.52",
      mpaa: "",
      plot: "A collection of short stories, made by different animators with robot as the working title.",
    },
    {
      trailer:
        '<a target="_blank" href="http://www.youtube.com/results?search_query=trailer+Timmy+Failure%3A+Mistakes+Were+Made+2020">trailer</a>',
      year: "2020",
      title: "Timmy Failure: Mistakes Were Made",
      imdb: "http://www.imdb.com/title/tt6820324",
      rating: "PG",
      genre: "Family, Comedy",
      actors: "Winslow Fegley, Ophelia Lovibond, Wallace Shawn",
      score: "6.1",
      quality: "HD",
      length: "99",
      gigs: "1.78",
      mpaa: "Rated PG for thematic elements, some language and mild action",
      plot: "An 11-year-old boy who believes that he is the best detective in town runs the agency Total Failures with his best friend, an imaginary 1,200-pound polar bear.",
    },
  ],
};

export default data